/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class it_polimi_elet_se_nomadikradio_Radio_Native_RadioResult */

#ifndef _Included_it_polimi_elet_se_nomadikradio_Radio_Native_RadioResult
#define _Included_it_polimi_elet_se_nomadikradio_Radio_Native_RadioResult
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
